### ISSUE TITLE
High CPU usage due to Memory map file missing

### ISSUE THREAD

**Issue by jshank** [waynieack/HikvisionZM#4]
After 12+ hours of running the script, CPU usage starts to go up and the following error repeats in the logs

`ERR [Memory map file '/dev/shm/zm.mmap.' does not exist.  zmc might not be running.]
Jun 25 10:34:36 zmbox motionstream.pl[20369]: Use of uninitialized value in concatenation (.) or string at /home/jshank/HikvisionZM/motionstream.pl line 307.
Jun 25 10:34:39 zmboxmotionstream.pl[20369]: Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/ZoneMinder/Memory/Mapped.pm line 87.`

I have pretty frequent restarts of the zmc processes but it doesn't look like the script is handling them gracefully.

**Comment by waynieack** [comment]
Yeah, its very difficult dealing with the memory map. The best thing to do
is to have the script restart when zoneminder restarts. The restart will
also refresh any settings you made to cameras in the script which is a plus.

I have an example of how to do it with monit in the help file on github,
its also possible to use systemd to start the script and have it depend on
zonemonder as well.


_Wayne

**Comment by jshank** [comment]
It's not related to a full zoneminder restart (which systemd is handling properly), it's just the untimely demise of a zmc instance for a particular camera. Zoneminder restarts the corresponding processes but the motionstream script doesn't get notified and hits a high CPU cycle trying to check the missing memory map file.

**Comment by waynieack** [comment]
I think its getting the error while just reading the memory (zmMemRead), I
can possibly look for an an error here and go into a 3 sec sleep loop to
wait for the zmc process to restart.

Is line 307 this "my $mr = zmMemRead($monitors->{$ip}->{'HASH'},
"shared_data:valid");" ?


Does it recover after zmc restarts?

**Comment by jshank** [comment]
307 is a print statement (below). It never recovers until I restart the script.

> 303          while ($mr!="1") {
> 304                  zmMemInvalidate($monitors->{$ip}->{'HASH'});
> 305                  my $mv =zmMemVerify($monitors->{$ip}->{'HASH'});
> 306                 if (!defined($mv)) {
> 307                     print ("Cant verify memory for ".$monitors->{$ip}->{'HASH'}->{Id}.", zoneminder may be stopped\n");
> 308                     $mr = 0; sleep 3;
> 309                 } else {
> 310                     print ("Reloading memory for ".$monitors->{$ip}->{'HASH'}->{Id}.", status of verify is:$mv\n");
> 311                     $mr = zmMemRead($monitors->{$ip}->{'HASH'}, "shared_data:valid");

**Comment by waynieack** [comment]
I think I might know whats happening, I was pulling the IP from the message
stream of the camera and I think it might have been getting corrupted for
some reason with your cameras. I changed the way I put the IP in the hash
and cleaned up the logging.

Grab the new version from Github and run it from the terminal, if the issue
happens again then send me the terminal logs from around the time when it
happened.

_Wayne

**Comment by waynieack** [comment]
I am not sure if the last change fixed your issue, but the latest update
should ensure that the high CPU issue does not happen any more.

Please pull the latest version and let me know if you still see the issue.

_Wayne

**Comment by jshank** [comment]
I pulled the update and am testing now. Will report back.

**Comment by jshank** [comment]
Working great so far. I'll give it a few more days and then update. Thanks!

**Comment by jshank** [comment]
Still lots of errors and processor usage with the newest version (1.2.1). Was using 80% of my processor. 

Jul 18 05:11:01 shanknas motionstream.pl[13411]: Use of uninitialized value in concatenation (.) or string at /home/jshank/HikvisionZM/motionstream.pl line
Jul 18 05:11:02 shanknas motionstream.pl[13411]: Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/ZoneMinder/Memory/Mapped.pm
Jul 18 05:11:02 shanknas motionstream[13411]: ERR [Memory map file '/dev/shm/zm.mmap.' does not exist.  zmc might not be running.]

**Comment by waynieack** [comment]
Can you send the line numbers the error is complaining about?

Also, are you seeing messages like "Error: Something went wrong in
validatemem"? If so send them.

I added verifications in the loop this time, grab the newest code and let
me know how it goes.

 I really have no idea whats happening on your system to make this happen.

-Wayne

**Comment by jshank** [comment]
Running the newest code. I'll provide feedback.

**Comment by jshank** [comment]
It's running and already consuming 33% of the processor but nothing in the log files or any indication it's failing. Is there any logging I can enable? To confirm, this is 1.2.2.

**Comment by waynieack** [comment]
This is my first and only threaded application and I have never been able to get the logging to file working, its very strange but I assume its related to the threads. 

On my system, I am not even able to pipe the terminal output to a file like: ./motionstream.pl >> /var/log/motionstream.log, if that works for you then this is the best option otherwise just run it and let it print out to the terminal as below.


To verify the version:

grep Version /home/jshank/HikvisionZM/motionstream.pl


The way I debug is to kill the current running copy:

killall motionstream.pl

Start it from the ssh terminal:

/home/jshank/HikvisionZM/motionstream.pl


On my system, it uses around 0.3-0.7 CPU, I am running 5 cameras. 

It runs completely in memory and I've seen high CPU with other programs when memory gets low, can you send the output of "free -h"?

 
The error "Use of uninitialized value in concatenation (.) or string at " indicates that a variable is undefined in the validatemem sub, but in the new code I verify every variable and return out of the sub if it is missing before the zmMemRead, so you should never get the "Memory map file '/dev/shm/zm.mmap.' does not exist" which is a result of running zmMemRead with $monitors->{$ip}->{'HASH'} being undefined. 

   unless (defined ($ip)) { print "$time - Error: Something went wrong in validatemem, IP is not defined."; return }
   unless (exists $monitors->{$ip}->{'HASH'}) { print "$ip - $time - Error: Something went wrong in validatemem, \$monitors->\{$ip\}->\{\'HASH\'\} is not defined"; return }
   unless (exists $monitors->{$ip}->{'HASH'}->{Id}) { print "$ip - $time - Error: Something went wrong in validatemem, \$monitors->\{$ip\}->\{\'HASH\'\}->\{\'Id\'\} is not defined"; return }
my $mr = zmMemRead($monitors->{$ip}->{'HASH'}, "shared_data:valid");

Let me know if you see the "Error: Something went wrong in validatemem" errors.

If you see any errors with line numbers, make sure to send the full error with the line number and if you can, grab the code from that line and send it as well.
